package com.cs407.tylerphelps.cs407hw2;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.cs407.tylerphelps.cs407hw2.CalDate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CAL_DATE.
*/
public class CalDateDao extends AbstractDao<CalDate, Long> {

    public static final String TABLENAME = "CAL_DATE";

    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Month = new Property(1, Integer.class, "month", false, "MONTH");
        public final static Property Day = new Property(2, Integer.class, "day", false, "DAY");
        public final static Property Year = new Property(3, Integer.class, "year", false, "YEAR");
        public final static Property Display = new Property(4, Boolean.class, "display", false, "DISPLAY");
    };


    public CalDateDao(DaoConfig config) {
        super(config);
    }
    
    public CalDateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'CAL_DATE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MONTH' INTEGER," + // 1: month
                "'DAY' INTEGER," + // 2: day
                "'YEAR' INTEGER," + // 3: year
                "'DISPLAY' INTEGER);"; // 4: display
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CAL_DATE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CalDate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer month = entity.getMonth();
        if (month != null) {
            stmt.bindLong(2, month);
        }
 
        Integer day = entity.getDay();
        if (day != null) {
            stmt.bindLong(3, day);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(4, year);
        }
 
        Boolean display = entity.getDisplay();
        if (display != null) {
            stmt.bindLong(5, display ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CalDate readEntity(Cursor cursor, int offset) {
        CalDate entity = new CalDate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // month
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // day
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // year
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0 // display
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CalDate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMonth(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setDay(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setYear(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setDisplay(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected Long updateKeyAfterInsert(CalDate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CalDate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
