package com.cs407.tylerphelps.cs407hw2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAL_DATE.
 */
public class CalDate {

    private Long id;
    private Integer month;
    private Integer day;
    private Integer year;
    private Boolean display;

    public CalDate() {
    }

    public CalDate(Long id) {
        this.id = id;
    }

    public CalDate(Long id, Integer month, Integer day, Integer year, Boolean display) {
        this.id = id;
        this.month = month;
        this.day = day;
        this.year = year;
        this.display = display;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Boolean getDisplay() {
        return display;
    }

    public void setDisplay(Boolean display) {
        this.display = display;
    }

}
