package com.cs407.tylerphelps.cs407hw2;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.cs407.tylerphelps.cs407hw2.Event;
import com.cs407.tylerphelps.cs407hw2.Date;

import com.cs407.tylerphelps.cs407hw2.EventDao;
import com.cs407.tylerphelps.cs407hw2.DateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig dateDaoConfig;

    private final EventDao eventDao;
    private final DateDao dateDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        dateDaoConfig = daoConfigMap.get(DateDao.class).clone();
        dateDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        dateDao = new DateDao(dateDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(Date.class, dateDao);
    }
    
    public void clear() {
        eventDaoConfig.getIdentityScope().clear();
        dateDaoConfig.getIdentityScope().clear();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public DateDao getDateDao() {
        return dateDao;
    }

}
